Fix requirements.txt.
The api for `pip.req.parse_requirements` is undocumented and has
changed in version 6, which leads to the following error.

```
TypeError: parse_requirements() missing 1 required keyword argument:
'session'
```

Instead we will use the [method][1] suggested by pip maintainer Donald
Stufft.

[1]: https://caremad.io/2013/07/setup-vs-requirement/